const data = [
    {
        "nome": "Player (Jogador)",
        "evento": "PVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Abelha-Rainha",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Creamy (Éter) + Mandrágora",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Angeling",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Orc Esqueleto",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Bafomé",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Barão Coruja",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Besouro-Ladrão Dourado",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Drainliar",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Cavaleiro Sanguinário",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Cavaleiro da Tempestade",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Ovo de Peco Peco",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Deviling",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Doppelganger",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Drake",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Vandon",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Drácula",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Eddga",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Drainliar",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Faraó",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Flor do Luar",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Freeoni",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Goblin",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "General",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Ovo de Peco Peco",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Goblin",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Hatii",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Goblin",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Jogadores",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Lorde das Trevas",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Vandon",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Maya",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Drainliar",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Osíris",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Vandon",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Hatti",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Goblin",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Gerente do Tempo",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Orc Herói",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Quimera",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Goblin",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Senhor dos Orcs",
        "evento": "MVP",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Salamandra",
        "evento": "Templo do Pesadelo",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Esquelo Operário + Vandon",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Gnomo",
        "evento": "Templo do Pesadelo",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Ovo de Peco Peco",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Wendine",
        "evento": "Templo do Pesadelo",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Goblin",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Sílfide",
        "evento": "Templo do Pesadelo",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Hidra",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Mestre Elementar",
        "evento": "Templo do Pesadelo",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Strouf",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "General",
        "evento": "Domínio Fantasma",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Creamy (Éter) + Flora",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Dragão Mutante",
        "evento": "Anomalia Espaço-Tempo",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Minorous + Petite",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    },
    {
        "nome": "Ódio",
        "evento": "Juperos",
        "chapeu": "",
        "face": "",
        "boca": "",
        "armadura": "",
        "arma": "Creamy (Éter) + Escorpião",
        "maoSecundaria": "",
        "capa": "",
        "calcado": "",
        "acessorio1": "",
        "acessorio2": "",
        "costas": ""
    }
];

