# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Angular Build

# {1}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {4}
      - name: Install dependencies
        run: npm ci
      # {5}
      # - name: Run tests
        # run: npm run test:ci
      # {6}
      - name: Build
        run: npm run build

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/card-combination-site
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
